export const trackedSites = [
  { name: "example.com", url: "https://example.com", readiness: 82, access: 91, discover: 76, savings: 24.3, lastAudit: "May 19, 9:42 AM" },
  { name: "docs.example.com", url: "https://docs.example.com", readiness: 78, access: 88, discover: 72, savings: 21.1, lastAudit: "May 18, 2:15 PM" },
  { name: "shop.example.com", url: "https://shop.example.com", readiness: 71, access: 85, discover: 68, savings: 19.4, lastAudit: "May 17, 11:30 AM" },
  { name: "blog.example.com", url: "https://blog.example.com", readiness: 88, access: 94, discover: 81, savings: 27.8, lastAudit: "May 19, 8:00 AM" },
  { name: "support.example.com", url: "https://support.example.com", readiness: 65, access: 79, discover: 61, savings: 16.2, lastAudit: "May 16, 4:45 PM" },
];

export const recentAudits = [
  { site: "example.com", time: "May 19, 9:42 AM", status: "Success", score: 82, size: "128 KB" },
  { site: "docs.example.com", time: "May 18, 2:15 PM", status: "Success", score: 78, size: "96 KB" },
  { site: "shop.example.com", time: "May 17, 11:30 AM", status: "Success", score: 71, size: "142 KB" },
  { site: "blog.example.com", time: "May 19, 8:00 AM", status: "Success", score: 88, size: "84 KB" },
];

export const activityTimeline = [
  { time: "9:42 AM", text: "Audit completed for example.com", type: "success" },
  { time: "9:40 AM", text: "Crawled 342 pages", type: "info" },
  { time: "9:38 AM", text: "Audit started for example.com", type: "info" },
  { time: "Yesterday", text: "Content change detected on docs.example.com", type: "warn" },
];

export const artifactLibrary = [
  { name: "llms.txt", desc: "LLMs Text File", status: "Success", freshness: "Fresh · 2h ago", size: "12.4 KB", generated: "May 19, 2026 9:42 AM" },
  { name: "llms-full.txt", desc: "Full Corpus", status: "Success", freshness: "Fresh · 2h ago", size: "48.2 KB", generated: "May 19, 2026 9:42 AM" },
  { name: "ai-index.json", desc: "Structured Index", status: "Success", freshness: "Fresh · 2h ago", size: "8.1 KB", generated: "May 19, 2026 9:42 AM" },
  { name: "pages/home.md", desc: "Page Mirror", status: "Success", freshness: "Fresh · 2h ago", size: "4.6 KB", generated: "May 19, 2026 9:42 AM" },
  { name: "pages/home.json", desc: "Structured Page", status: "Success", freshness: "Fresh · 2h ago", size: "2.1 KB", generated: "May 19, 2026 9:42 AM" },
];

export const llmsPreview = `# example.com — AI-Friendly Content Map

> Generated by glasgate.ai

## Overview
- Purpose: Business website content
- Audience: Customers and AI agents
- Focus: Products, docs, pricing

## Key Sections
- [Home](/) — Main landing page
- [Products](/products) — Product catalog
- [Docs](/docs) — Documentation`;

export const logEvents = [
  { time: "9:42 AM", event: "Audit Run Completed", source: "example.com", details: "Score 82/100 · 5 pages", status: "Success", severity: "Info" },
  { time: "9:40 AM", event: "Crawl Event", source: "example.com", details: "342 pages crawled", status: "Success", severity: "Info" },
  { time: "9:35 AM", event: "Content Change Detected", source: "docs.example.com", details: "3 pages updated", status: "Success", severity: "Medium" },
  { time: "8:12 AM", event: "Freshness Alert", source: "shop.example.com", details: "Stale content > 30 days", status: "Warning", severity: "Medium" },
  { time: "7:55 AM", event: "Bot Access", source: "example.com", details: "GlassGateBot allowed", status: "Success", severity: "Info" },
];

export const recommendations = [
  { impact: "High", title: "Add Product schema to 142 pages", category: "Schema", progress: "12 / 142", assignee: "Alex Kim", initials: "AK" },
  { impact: "High", title: "Fix 342 broken internal links", category: "Internal Links", progress: "28 / 342", assignee: "Sarah Chen", initials: "SC" },
  { impact: "High", title: "Block 28 non-crawlable pages", category: "Crawl Access", progress: "5 / 28", assignee: "Marcus Johnson", initials: "MJ" },
  { impact: "Medium", title: "Resolve 96 duplicate pages", category: "Canonical", progress: "12 / 96", assignee: "Alex Kim", initials: "AK" },
  { impact: "Medium", title: "Improve headings on 128 pages", category: "Content Structure", progress: "34 / 128", assignee: "Sarah Chen", initials: "SC" },
  { impact: "Low", title: "Add meta descriptions to 64 pages", category: "Content Structure", progress: "20 / 64", assignee: "Marcus Johnson", initials: "MJ" },
];

export const teamMembers = [
  { name: "Alex Kim", email: "admin@glasgate.ai", role: "Owner", status: "Active", lastActive: "Now" },
  { name: "Sarah Chen", email: "sarah@acmecorp.com", role: "Admin", status: "Active", lastActive: "2h ago" },
  { name: "Marcus Johnson", email: "marcus@acmecorp.com", role: "Editor", status: "Active", lastActive: "Yesterday" },
  { name: "Emily Davis", email: "emily@acmecorp.com", role: "Viewer", status: "Active", lastActive: "3 days ago" },
];

export const pendingInvites = [
  { name: "Jordan Lee", email: "jordan@acmecorp.com", role: "Editor", sent: "2 days ago" },
  { name: "Taylor Smith", email: "taylor@acmecorp.com", role: "Viewer", sent: "5 days ago" },
];

export const usageMetrics = [
  { label: "Audits Run", value: "24", limit: "Unlimited" },
  { label: "Pages Crawled", value: "12,842", limit: "Unlimited" },
  { label: "Data Processed", value: "8.7 GB", limit: "Unlimited" },
  { label: "Storage Used", value: "28.4 GB", limit: "Unlimited" },
  { label: "Team Seats", value: "6", limit: "12", percent: 50 },
];

export const invoices = [
  { id: "INV-2025-05", date: "May 1, 2025", amount: "$0.00", status: "Paid" },
  { id: "INV-2025-04", date: "Apr 1, 2025", amount: "$0.00", status: "Paid" },
  { id: "INV-2025-03", date: "Mar 1, 2025", amount: "$0.00", status: "Paid" },
];

export const siteArtifacts = [
  { name: "pages.json", type: "Structured Data", generated: "May 19, 9:42 AM", status: "Success", size: "24 KB" },
  { name: "content.md", type: "Cleaned Content", generated: "May 19, 9:42 AM", status: "Success", size: "18 KB" },
  { name: "faqs.json", type: "Structured Data", generated: "May 19, 9:42 AM", status: "Success", size: "6 KB" },
  { name: "llms.txt", type: "Generated Index", generated: "May 19, 9:42 AM", status: "Success", size: "12 KB" },
  { name: "ai-index.json", type: "Structured Index", generated: "May 19, 9:42 AM", status: "Success", size: "8 KB" },
];

export const readinessChecks = [
  { label: "Content Structure", status: "Good" },
  { label: "Metadata Quality", status: "Good" },
  { label: "Internal Linking", status: "Needs Work" },
  { label: "Content Freshness", status: "Good" },
  { label: "Technical Health", status: "Good" },
];

export const topRecommendations = [
  { title: "Add Schema Markup", desc: "Implement JSON-LD on key product pages.", impact: "High Impact" },
  { title: "Improve Content Visibility", desc: "Ensure critical pages are linked from navigation.", impact: "Medium Impact" },
  { title: "Optimize Access Controls", desc: "Review robots.txt for AI crawler permissions.", impact: "Medium Impact" },
];
