/**
 * Generate llms.txt — the AI-readable site index (plain text / Markdown format).
 * See https://llmstxt.org for the spec.
 */

export function generateLlmsTxt(siteData, siteId) {
  const now = new Date().toISOString();
  const lines = [];

  // Title
  lines.push(`# ${siteData.title || siteData.url}`);
  lines.push("");

  // Description
  if (siteData.description) {
    lines.push(`> ${siteData.description}`);
    lines.push("");
  }

  // Core pages
  lines.push("## Core Pages");
  lines.push("");
  for (const page of siteData.pages) {
    const desc = page.description ? ` — ${page.description}` : "";
    lines.push(`- [${page.title || page.url}](${page.url})${desc}`);
  }
  lines.push("");

  // Agent-readable mirrors (pointing to GlassGate-generated files)
  lines.push("## Agent-readable Mirrors");
  lines.push("");
  lines.push(`- [Full Markdown Corpus](/generated/${siteId}/llms-full.txt)`);
  lines.push(`- [AI Index JSON](/generated/${siteId}/ai-index.json)`);
  lines.push("");

  // Per-page mirrors
  if (siteData.pageSlugs && siteData.pageSlugs.length > 0) {
    lines.push("## Page Mirrors");
    lines.push("");
    for (const { url, slug, title } of siteData.pageSlugs) {
      lines.push(`- [${title || url}](${url}) → [.md](/generated/${siteId}/pages/${slug}.md) [.json](/generated/${siteId}/pages/${slug}.json)`);
    }
    lines.push("");
  }

  // Usage note
  lines.push("## Usage Notes");
  lines.push("");
  lines.push("This file is generated by glasgate.ai and points to public,");
  lines.push("canonical-aware representations of the visible website content.");
  lines.push("All mirrors match the content visible to human users.");
  lines.push(`Last updated: ${now}`);
  lines.push("");

  return lines.join("\n");
}
