/**
 * Generate llms.txt — curated AI discovery map (not a content dump).
 * See https://llmstxt.org
 */

export function generateLlmsTxt(siteData, siteId, options = {}) {
  const now = new Date().toISOString().split("T")[0];
  const baseUrl = siteData.url.replace(/\/$/, "");
  const curated = options.curatedPages || siteData.pages.slice(0, 8);
  const crawled = siteData.pageSlugs || [];
  const lines = [];

  lines.push(`# ${siteData.title || baseUrl}`);
  lines.push("");

  if (siteData.description) {
    lines.push(`> ${siteData.description}`);
    lines.push("");
  }

  lines.push("## Important Pages");
  lines.push("");
  for (const page of curated) {
    const desc = page.description ? ` - ${page.description}` : "";
    lines.push(`- [${page.title || page.url}](${page.url})${desc}`);
  }
  lines.push("");

  lines.push("## AI-readable Files");
  lines.push("");
  lines.push(`- [Full Markdown Corpus](${baseUrl}/llms-full.txt)`);
  lines.push(`- [AI Index](${baseUrl}/ai-index.json)`);
  lines.push("");

  if (crawled.length > 0) {
    lines.push("## Page Mirrors");
    lines.push("");
    for (const { slug, title, url } of crawled) {
      lines.push(`- [${title || slug} Markdown](${baseUrl}/pages/${slug}.md)`);
      lines.push(`- [${title || slug} JSON](${baseUrl}/pages/${slug}.json)`);
    }
    lines.push("");
  }

  lines.push("## Usage Notes");
  lines.push("");
  lines.push("Content is generated from public, visible, canonical pages only.");
  lines.push("Login, cart, search, filter, and tracking URLs are excluded.");
  lines.push(`Generated by glasgate.ai on ${now}.`);
  lines.push(`Hosted mirrors: /generated/${siteId}/`);
  lines.push("");

  return lines.join("\n");
}
